<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<meta http-equiv="X-UA-Compatible" content="IE=edge">
<title>Alegra||Contactos</title>
<meta name="description" content="">
<meta name="author" content="">
  
<!-- Hero Slider -->
<link href="/DESAROLLO/Alegra/public/assets/sliders/hero-slider/heroslider.css" rel="stylesheet">

<!-- Bootstrap CSS -->
<link href="/DESAROLLO/Alegra/public/assets/bootstrap/css/bootstrap.min.css" rel="stylesheet">

<!-- Icon Fonts -->
<link href="/DESAROLLO/Alegra/public/assets/fonts/font-awesome/css/font-awesome.min.css" rel="stylesheet" media="screen">
<link href="/DESAROLLO/Alegra/public/assets/fonts/flaticon/flaticon.css" rel="stylesheet" media="screen">

<!-- CSS animations -->
<link href="/DESAROLLO/Alegra/public/assets/css/animate.css" rel="stylesheet">
<link href="/DESAROLLO/Alegra/public/assets/css/hover-effect.css" rel="stylesheet">

<!-- Theme CSS -->
<link href="/DESAROLLO/Alegra/public/assets/css/styles.css" rel="stylesheet">
<link href="/DESAROLLO/Alegra/public/assets/css/master_style.css" rel="stylesheet">
<link href="/DESAROLLO/Alegra/public/assets/css/header-1.css" rel="stylesheet">
<link href="/DESAROLLO/Alegra/public/assets/css/colors/mint.css" id="colors" rel="stylesheet">
<link href="/DESAROLLO/Alegra/public/assets/css/colors/backgrounds/bg-mint.css" id="backgrounds" rel="stylesheet">
<link href="/DESAROLLO/Alegra/public/assets/css/responsive.css" rel="stylesheet">
<link href="/DESAROLLO/Alegra/public/assets/js/switcher/switcher.css" rel="stylesheet">

<!--[if IE]>
<link href="assets/css/ie.css" rel="stylesheet">
<![endif]-->

<!-- Favicon -->
<link href="/DESAROLLO/Alegra/public/assets/images/favicon/apple-touch-icon-144.png" sizes="144x144" rel="apple-touch-icon-precomposed">
<link href="/DESAROLLO/Alegra/public/assets/images/favicon/apple-touch-icon-114.png" sizes="114x114" rel="apple-touch-icon-precomposed">
<link href="/DESAROLLO/Alegra/public/assets/images/favicon/apple-touch-icon-72.png" sizes="72x72" rel="apple-touch-icon-precomposed">
<link href="/DESAROLLO/Alegra/public/assets/images/favicon/apple-touch-icon-57.png" rel="apple-touch-icon-precomposed">
<link href="/DESAROLLO/Alegra/public/assets/images/favicon.ico" rel="shortcut icon">

</head>

<body>
<!-- #page-wrap -->
<div id="page-wrap">

  <!-- #top-bar -->
  <section id="top-bar">
  <!-- .container -->
  <div class="container">
    <!-- .row -->
    <div class="row">
      <div class="col-xs-12">
        <!-- .row -->
        <div class="row">
          <!-- .top-bar-info-content -->
          <div class="top-bar-info-content col-xs-12 col-sm-6">
            <ul class="list-unstyled list-inline">
              <li><span>Phone: (213) 123 4456</span></li>
              <li><span>Email: info@alegra.com</span></li>
            </ul>
          </div>
          <!-- /.top-bar-info-content -->
          <!-- .top-bar-search-content -->
          <div class="top-bar-search-content col-xs-12 col-sm-3 col-md-4">
            <div id="sb-search" class="sb-search">
              <form>
                <input class="sb-search-input" placeholder="Search..." type="text" value="" name="search" id="search">
                <input class="sb-search-submit" type="submit" value="">
                <span class="sb-icon-search"></span>
              </form>
            </div>
          </div>
          <!-- /.top-bar-search-content -->
          <!-- .top-bar-links-content -->
          <div class="top-bar-links-content col-xs-12 col-sm-3 col-md-2">
            <ul class="list-unstyled list-inline">
              <li><a href="#"><i class="fa fa-lock"></i> Sign in</a></li>
              <li><a href="#">Sign up</a></li>
            </ul>
          </div>
          <!-- /.top-bar-links-content -->
        </div>
        <!-- /.row -->
      </div>
    </div>
    <!-- /.row -->
  </div>
  <!-- /.container -->
  </section>
  <!-- /#top-bar -->

  <!-- #navbar-1 -->
  <div id="navbar-1">
    <!-- .navbar -->
    <nav id="navbar" class="navbar navbar-default navbar-static" role="navigation">
    <!-- .container -->
    <div class="container">
      <!-- .row -->
      <div class="row">
        <div class="col-xs-12">
          <!-- .navbar-header -->
          <div class="navbar-header">
            <!-- .navbar-toggle -->
            <button class="navbar-toggle" type="button" data-toggle="collapse" data-target=".js-navbar-collapse" aria-expanded="false" aria-controls="navbar"><span class="sr-only">Toggle navigation</span><span class="icon-bar top-bar"></span><span class="icon-bar middle-bar"></span><span class="icon-bar bottom-bar"></span></button>
            <!-- /.navbar-toggle -->
            <!-- .navbar-brand -->
            <a class="navbar-brand" href="#"><img src="/DESAROLLO/Alegra/public/assets/images/alegra_logo.png" alt=""></a>
            <!-- /.navbar-brand -->
          </div>
          <!-- /.navbar-header -->
          <!-- .navbar-collapse -->
          <div class="collapse navbar-collapse js-navbar-collapse">
            <!-- .navbar-nav -->
            <ul class="nav navbar-nav navbar-right">
              <!-- .dropdown -->
              <li class="dropdown"><a href="#" class="dropdown-toggle" data-toggle="dropdown">Inicio <span></span></a>
 
              </li>           
             <li class="dropdown"><a href="#" class="dropdown-toggle" data-toggle="dropdown">Ingresos <span class="fa fa-angle-down"></span></a>
              <ul class="dropdown-menu">
                <li><a href="#">Factura de Venta</a></li>
                <li class="divider"></li>
                <li><a href="#">Facturas recurrente</a></li>
                <li class="divider"></li>
                <li><a href="#">Pagos recibidos</a></li>
                <li class="divider"></li>
                <li><a href="#">Notas crédito</a></li>
                <li class="divider"></li>
                <li><a href="#">Cotizaciones</a></li>
                <li class="divider"></li>
                <li><a href="#">Remisiones</a></li>
                <li class="divider"></li>
                <li><a href="#">POS</a></li>
              </ul>
              </li>
              <!-- /.dropdown -->
              <!-- .dropdown -->
              <li class="dropdown"><a href="#" class="dropdown-toggle" data-toggle="dropdown">Gastos <span class="fa fa-angle-down"></span></a>
              <ul class="dropdown-menu">
                <li><a href="#">Pagos</a></li>
                <li class="divider"></li>
                <li><a href="#">Facturas de proveedores</a></li>
                <li class="divider"></li>
                <li><a href="#">Pagos recurrentes</a></li>
                <li class="divider"></li>
                <li><a href="#">Notas débito</a></li>
                <li class="divider"></li>
                <li><a href="#">Órdenes de compra</a></li>
              </ul>
              </li>
              <!-- /.dropdown -->
              <li class="active dropdown"><a href="#" class="dropdown-toggle" data-toggle="dropdown">Contactos <span></span></a>
              </li>  
              <!-- .dropdown -->
              <li class="dropdown"><a href="#" class="dropdown-toggle" data-toggle="dropdown">Inventario <i class="fa fa-angle-down"></i></a>
              <ul class="dropdown-menu">
                <li class="divider"></li>
                <li><a href="#">Items de venta</a></li>
                <li class="divider"></li>
                <li><a href="#">Valor de inventario</a></li>
                <li class="divider"></li>
                <li><a href="#">Ajuste a inventario</a></li>
                <li class="divider"></li>
                <li><a href="#">Gestion de items</a></li>
                <li class="divider"></li>
                <li><a href="#">Listas de precio</a></li>
                <li class="divider"></li>
                <li><a href="#">Bodegas</a></li>
              </ul>
              </li>
              <!-- /.dropdown -->
              <!-- .dropdown -->
              <li class="dropdown"><a href="#" class="dropdown-toggle" data-toggle="dropdown">Bancos<span></span></a>
              </li>  
    
              <!-- /.dropdown -->
              <!-- .dropdown -->
              <li class="dropdown"><a href="#" class="dropdown-toggle" data-toggle="dropdown">Categorías <i class="fa fa-angle-down"></i></a>
              <ul class="dropdown-menu">
                <li class="divider"></li>
                <li><a href="#">Categorías</a></li>
                <li class="divider"></li>
                <li><a href="#">Ajuste de Categorias</a></li>
              </ul>
              </li>
              <!-- /.dropdown -->
              <!-- .dropdown -->
              <li class="dropdown"><a href="#" class="dropdown-toggle" data-toggle="dropdown">Reportes</a>
              </li>
              <!-- /.dropdown -->
            </ul>
            <!-- /.navbar-nav -->
          </div>
          <!-- /.navbar-collapse -->
        </div>
        <!-- /.row -->
      </div>
    </div>
    <!-- /.container -->
    </nav>
    <!-- /.navbar -->
  </div>
  <!-- /#navbar-1 -->


  <?php echo $this->content; ?>


  <!-- #footer-1 -->
  <footer id="footer-1">
  <!-- .container -->
  <div class="container">
    <!-- .row -->
    <div class="row clearfix footer-1-content">
      <div class="col-xs-12 col-md-3">
        <h3 class="footer-1-logo"><img src="/DESAROLLO/Alegra/public/assets/images/alegra_logo.png" alt=""></h3>
         
        <!-- .social-icons-2 -->
        <div class="social-icons-2">
          <a href="#" class="icon-facebook" data-toggle="tooltip" data-placement="top" title="Facebook"><i class="fa fa-facebook"></i></a>
          <a href="#" class="icon-twitter" data-toggle="tooltip" data-placement="top" title="Twitter"><i class="fa fa-twitter"></i></a>
          <a href="#" class="icon-google-plus" data-toggle="tooltip" data-placement="top" title="Google Plus"><i class="fa fa-google-plus"></i></a>
        </div>
        <!-- /.social-icons-2 -->
      </div>
      <div class="col-xs-12 col-md-3">
        <h3>Ayudas Paso a Paso</h3>
        <ul class="list-unstyled">
          <li>
           <i class="fa fa-angle-double-right"></i> <a href="#">Cómo crear una factura de venta</a>
          </li>
          <li>
            <i class="fa fa-angle-double-right"></i> <a href="#">Cómo crear una factura de proveedor</a>
          </li>
          <li>
            <i class="fa fa-angle-double-right"></i> <a href="#">Cómo importar contactos</a>
          </li>
          <li>
           <i class="fa fa-angle-double-right"></i> <a href="#">Cómo crear una cuenta de Banco</a>
          </li>
          <li>
           <i class="fa fa-angle-double-right"></i> <a href="#">Cómo registrar un pago a una factura de venta</a>
          </li>
          <li>
            <i class="fa fa-angle-double-right"></i> <a href="#">Cómo crear una nota crédito</a>
          </li>
        </ul>
      </div>
      <div class="col-xs-12 col-md-3">
        <h3>Soporte</h3>
        <!-- .footer-1-contact-icons -->
        <ul class="list-unstyled">
        <li>
         <i class="fa fa-angle-double-right"></i> <a href="#">Contáctanos</a>
        </li>
        <li>
          <i class="fa fa-angle-double-right"></i> <a href="#">Centro de ayuda</a>
        </li>
        <li>
          <i class="fa fa-angle-double-right"></i> <a href="#">Manual de primeros </a>
        </li>
        <li>
         <i class="fa fa-angle-double-right"></i> <a href="#">Pasos en Alegra</a>
        </li>
        <li>
         <i class="fa fa-angle-double-right"></i> <a href="#">Plan de referidos</a>
        </li>
        <li>
          <i class="fa fa-angle-double-right"></i> <a href="#">Comparte tu historia</a>
        </li>
      </ul>
        <!-- /.footer-1-contact-icons -->
      </div>
      <div class="col-xs-12 col-md-3">
        <h3>Contactos</h3>
        <ul class="list-unstyled footer-1-contact-icons">
          <li><span><i class="fa fa-phone"></i></span> (213) 123 4456</li>
          <li><span><i class="fa fa-envelope-o"></i></span> info@alegra.com</li>
          <li><span><i class="fa fa-skype"></i></span> alegra_skype</li>
          <li><span><i class="fa fa-street-view"></i></span> Orange, CA, USA</li>
        </ul>
        <p>
          Envianos tu Email.
        </p>
        <!-- .form-input-group-addon -->
        <div class="form-input-group-addon">
          <!-- .form-subscribe -->
          <div class="form-subscribe">
            <!-- .form-subscribe-content -->
            <div class="form-subscribe-content">
              <div class="message">
              </div>
              <!-- form -->
              <form class="form-horizontal subscribe">
                <div class="input-group">
                  <input type="email" class="form-control email input-md" name="email" placeholder="Your Email">
                  <span class="input-group-addon">
                  <button type="submit" name="submit" class="SendButton btn btn-custom btn-md"><i class="fa fa-envelope-o"></i></button>
                  </span>
                </div>
              </form>
              <!-- /form -->
            </div>
            <!-- /.form-subscribe-content -->
          </div>
          <!-- /.form-subscribe -->
        </div>
        <!-- /.form-input-group-addon -->
      </div>
    </div>
    <!-- /.row -->
  </div>
  <!-- /.container -->
  <!-- .footer-1-copyright -->
  <div class="clearfix footer-1-copyright">
    <!-- .container -->
    <div class="container">
      <!-- .row -->
      <div class="row">
        <div class="col-xs-12">
          <p class="text-center">
            &copy; 2017 Alegra.com</a>
          </p>
        </div>
      </div>
      <!-- /.row -->
    </div>
    <!-- /.container -->
  </div>
  <!-- /.footer-1-copyright -->
  </footer>
  <!-- /#footer-1 -->

</div>
<!-- /#page-wrap -->

<!-- JavaScript -->
<!-- Placed at the end of the document so the pages load faster -->
<script src="/DESAROLLO/Alegra/public/assets/js/jquery-1.12.0.min.js"></script>
<script src="/DESAROLLO/Alegra/public/assets/bootstrap/js/bootstrap.min.js"></script>
<script src="/DESAROLLO/Alegra/public/assets/js/switcher/switcher.js"></script>
<script src="/DESAROLLO/Alegra/public/php/mcapi-subscribe/js/mailing-list.js"></script>
<script src="/DESAROLLO/Alegra/public/assets/js/modernizr.js"></script>
<script src="/DESAROLLO/Alegra/public/assets/js/classie.js"></script>
<script src="/DESAROLLO/Alegra/public/assets/js/uisearch.js"></script>
<script src="/DESAROLLO/Alegra/public/assets/js/theme-scripts/scripts-search-form.js"></script>
<script src="/DESAROLLO/Alegra/public/assets/sliders/hero-slider/jquery.heroslider.js"></script>
<script src="/DESAROLLO/Alegra/public/assets/js/jquery.inview.js"></script>
<script src="/DESAROLLO/Alegra/public/assets/js/theme-scripts/scripts-numeral-counter.js"></script>
<script src="/DESAROLLO/Alegra/public/assets/js/jquery.touchswipe.min.js"></script>
<script src="/DESAROLLO/Alegra/public/assets/js/theme-scripts/scripts-touchswipe.js"></script>
<script src="/DESAROLLO/Alegra/public/assets/js/theme-scripts/scripts-tooltip.js"></script>
<script src="/DESAROLLO/Alegra/public/assets/js/theme-scripts/scripts.js"></script>
</body>
</html>